### ISSUE TITLE
Resolve linting for license

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snitch_cluster#5]
In github workflows, the license checker is tailored towards PULP checking. We need to make a separate one for our side OR need to resolve the licensing checks for files that do not have licenses. For now we add in the exclude list the files we don't want to change.

Check: https://github.com/KULeuven-MICAS/snitch_cluster/blob/main/.github/workflows/lint.yml

```yaml
#################
# Check License #
#################
license-lint:
  name: Check License headers
  runs-on: ubuntu-latest
  steps:
    - name: Check License
      uses: pulp-platform/pulp-actions/lint-license@v2.1.0
      with:
        patches: 0001-Allow-hash-comments-in-assembly.patch
        # We cover ETH Zurich and lowRISC licenses and Apache 2.0
        # (mostly for SW) and Solderpad for the hardware.
        # yamllint disable rule:line-length
        license: |
          Copyright (\d{4}(-\d{4})?\s)?(ETH Zurich and University of Bologna|lowRISC contributors).
          (Solderpad Hardware License, Version 0.51|Licensed under the Apache License, Version 2.0), see LICENSE for details.
          SPDX-License-Identifier: (SHL-0.51|Apache-2.0)
        # yamllint enable rule:line-length
        match_regex: true
        exclude_paths: |
          sw/snRuntime/src/omp/interface.h
          sw/math/arch/generic/*
          sw/math/arch/riscv64/bits/*
          sw/math/include/*
          sw/math/src/include/*
          sw/math/src/internal/*
          sw/math/src/math/*
          sw/math/Makefile
          hw/snitch/src/csr_snax_def.sv
```
